# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d13330e0e34d870c16ebaf279dcd54d1"
name = "PODesk: Purchase Orders"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/privacy/customers/data_request"
  topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/privacy/customers/redact"
  topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/privacy/shop/redact"
  topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_orders,read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
